import { Metadata } from "next";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "صحفه ورود",
  description: "Generated by create next app",
};

const ClientComponent = dynamic(
  () => import("./components/ClientFormComponent"),
  { ssr: false }
);
export default function LoginPage() {
  return <ClientComponent />;
}
