import { Metadata } from "next";
import LoginPage from "../login/components/ClientFormComponent";

export const metadata: Metadata = {
  title: "صحفه ورود",
  description: "Generated by create next app",
};

export default async function SignUpPage() {
  // async function createSessionClient(formData) {
  //   "use server";
  //   const data = Object.fromEntries(formData);
  //   const { email, password, name } = data;

  //   try {
  //     const response = await axiosInstance.post("/account", {
  //       userId: ID.unique(),
  //       email,
  //       password,
  //       name,
  //     });

  //     if (response.status === 201) {
  //       const loginResponse = await axiosInstance.post(
  //         "/account/sessions/email",
  //         {
  //           email,
  //           password,
  //         }
  //       );

  //       const setCookieHeader = loginResponse.headers["set-cookie"];
  //       if (setCookieHeader) {
  //         // ذخیره کوکی در مرورگر
  //         cookies().set("whoAmI", setCookieHeader[0]);
  //         // افزودن await در redirect تا از انجام ریدایرکت اطمینان حاصل شود
  //       }
  //     }
  //   } catch (error) {
  //     console.error("Error during signup or login:", error);
  //   }
  //   return redirect("/");
  // }
  return <LoginPage />;
}
