import type { Metadata } from "next";
// import "./globals.css";

export const metadata: Metadata = {
  icons: "../public/logo.png",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutDashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
